Pages/User/AccountActivity.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using insecure_bank_net.Bean;
using insecure_bank_net.Dao;
using insecure_bank_net.Facade;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace insecure_bank_net.Pages.User
{
    public class AccountActivity : PageModel
    {
        private readonly IAuthenticationFacade authenticationFacade;
        private readonly IAccountDao accountDao;
        private readonly ICashAccountDao cashAccountDao;
        private readonly IActivityDao activityDao;

        public Bean.Account Account { get; set; }

        public List<Transaction> FirstCashAccountTransfers { get; set; }

        public List<SelectListItem> CashAccounts { get; set; }

        public string ActualCashAccountNumber { get; set; }

        [BindProperty] public string Number { get; set; }

        public AccountActivity(IAuthenticationFacade authenticationFacade, IAccountDao accountDao,
            ICashAccountDao cashAccountDao, IActivityDao activityDao)
        {
            this.authenticationFacade = authenticationFacade;
            this.accountDao = accountDao;
            this.cashAccountDao = cashAccountDao;
            this.activityDao = activityDao;
        }

        public void OnGet(string number)
        {
            ShowAccount(number);
        }

        public void OnPost()
        {
            ShowAccount(Number);
        }

        private void ShowAccount(string number)
        {
            var principal = authenticationFacade.GetPrincipal();
            var account = accountDao.FindUsersByUsername( principal.Identity!.Name).First();
            var cashAccounts = cashAccountDao.FindCashAccountsByUsername(account.Username);

            var cashAccount = number ?? cashAccounts.First().Number;
            var firstCashAccountTransfers = activityDao.FindTransactionsByCashAccountNumber(cashAccount);
            Account = account;
            FirstCashAccountTransfers = Enumerable.Reverse(firstCashAccountTransfers).ToList();
            ActualCashAccountNumber = number;
            CashAccounts = cashAccounts.Select(item => new SelectListItem
            {
                Text = $"{item.Number} ({item.Description})",
                Value = item.Number,
                Selected = item.Number == number
            }).ToList();
        }
    }
}

Pages/User/Admin.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using insecure_bank_net.Dao;
using insecure_bank_net.Facade;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace insecure_bank_net.Pages.User
{
    public class Admin : PageModel
    {
        private readonly IAuthenticationFacade authenticationFacade;
        private readonly IAccountDao accountDao;

        public Bean.Account Account { get; set; }
        
        public List<Bean.Account> Accounts { get; set; }
        
        public Admin(IAuthenticationFacade authenticationFacade, IAccountDao accountDao)
        {
            this.authenticationFacade = authenticationFacade;
            this.accountDao = accountDao;
        }

        public void OnGet()
        {
            var principal = authenticationFacade.GetPrincipal();
            Account = accountDao.FindUsersByUsername(principal.Identity!.Name).First();
            Accounts = accountDao.FindAllUsers();
        }
    }
}

Pages/User/CreditActivity.cshtml.cs
using System.Linq;
using insecure_bank_net.Dao;
using insecure_bank_net.Facade;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace insecure_bank_net.Pages.User
{
    public class CreditActivity : PageModel
    {
        private readonly IAuthenticationFacade authenticationFacade;
        private readonly IAccountDao accountDao;

        public Bean.Account Account { get; set; }
            
        public string ActualCreditCardNumber { get; set; }

        [BindProperty]
        public string Number { get; set; }
        
        public CreditActivity(IAuthenticationFacade authenticationFacade, IAccountDao accountDao)
        {
            this.authenticationFacade = authenticationFacade;
            this.accountDao = accountDao;
        }
        
        public void OnGet(string number)
        {
            var principal = authenticationFacade.GetPrincipal();
            var account = accountDao.FindUsersByUsername(principal.Identity!.Name).First();
            Account = account;
            ActualCreditCardNumber = number;
        }
    }
}

Pages/User/Dashboard.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using insecure_bank_net.Bean;
using insecure_bank_net.Dao;
using insecure_bank_net.Facade;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace insecure_bank_net.Pages.User
{
    public class Dashboard : PageModel
    {
        private readonly IAuthenticationFacade authenticationFacade;
        private readonly IAccountDao accountDao;
        private readonly ICashAccountDao cashAccountDao;
        private readonly ICreditAccountDao creditAccountDao;

        public Dashboard(IAuthenticationFacade authenticationFacade, IAccountDao accountDao,
            ICashAccountDao cashAccountDao, ICreditAccountDao creditAccountDao)
        {
            this.authenticationFacade = authenticationFacade;
            this.accountDao = accountDao;
            this.cashAccountDao = cashAccountDao;
            this.creditAccountDao = creditAccountDao;
        }

        public Bean.Account Account { get; set; }

        public List<CashAccount> CashAccounts { get; set; }

        public List<CreditAccount> CreditAccounts { get; set; }

        public void OnGet()
        {
            var principal = authenticationFacade.GetPrincipal();
            var account = accountDao.FindUsersByUsername(principal.Identity!.Name).First();
            var cashAccounts = cashAccountDao.FindCashAccountsByUsername(account.Username);
            var creditAccounts = creditAccountDao.FindCreditAccountsByUsername(account.Username);
            Account = account;
            CashAccounts = cashAccounts;
            CreditAccounts = creditAccounts;
        }
    }
}

Pages/User/NewTransfer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using insecure_bank_net.Bean;
using insecure_bank_net.Dao;
using insecure_bank_net.Facade;
using insecure_bank_net.Util;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace insecure_bank_net.Pages.User
{
    public class NewTransfer : PageModel
    {
        private const string PENDING_TRANSFER = "PENDING_TRANSFER";

        private readonly IAuthenticationFacade authenticationFacade;
        private readonly IAccountDao accountDao;
        private readonly ICashAccountDao cashAccountDao;
        private readonly ITransferFacade transferFacade;

        public Bean.Account Account { get; set; }

        public List<SelectListItem> CashAccounts { get; set; }

        public string Type { get; set; }

        [BindProperty] public Transfer Transfer { get; set; }

        [BindProperty] public OperationConfirm Confirm { get; set; }

        public NewTransfer(IAuthenticationFacade authenticationFacade, ITransferFacade transferFacade, IAccountDao accountDao, ICashAccountDao cashAccountDao)
        {
            this.authenticationFacade = authenticationFacade;
            this.transferFacade = transferFacade;
            this.accountDao = accountDao;
            this.cashAccountDao = cashAccountDao;
        }

        public void OnGet()
        {
            var principal = authenticationFacade.GetPrincipal();
            var account = accountDao.FindUsersByUsername(principal.Identity!.Name).First();
            var cashAccounts = cashAccountDao.FindCashAccountsByUsername(account.Username);
            Account = account;
            CashAccounts = cashAccounts.Select(item => new SelectListItem
            {
                Text = $"{item.Number} ({item.Description})",
                Value = item.Number
            }).ToList();
            Transfer = new Transfer();
            Response.Cookies.Append("accountType", AccountType.PERSONAL);
        }

        public IActionResult OnPostTransfer()
        {
            if (Transfer.Amount <= 0)
            {
                ModelState.AddModelError("Input.Amount", "You must enter a positive amount");
            }

            if (ModelState.ErrorCount > 0)
            {
                OnGet();
                return Page();
            }

            var principal = authenticationFacade.GetPrincipal();
            Account = accountDao.FindUsersByUsername(principal.Identity!.Name).First();

            var accountType = Request.Cookies["accountType"] ?? AccountType.PERSONAL;
            return accountType.Equals(AccountType.PERSONAL)
                ? TransferCheck(Transfer)
                : TransferConfirmation(Transfer, accountType);
        }

        public IActionResult OnPostConfirm()
        {
            var json = Encoding.UTF8.GetString(HttpContext.Session.Get(PENDING_TRANSFER));
            HttpContext.Session.Remove(PENDING_TRANSFER);
            var transfer = JsonSerializer.Deserialize<Transfer>(json);
            
            if ("Confirm".Equals(this.Confirm.Action))
            {
                var accountType = Request.Cookies["accountType"] ?? AccountType.PERSONAL;
                return TransferConfirmation(transfer, accountType);
            }

            return RedirectToPage("/User/NewTransfer");
        }

        private IActionResult TransferCheck(Transfer transfer)
        {
            Transfer = transfer;
            Confirm = new OperationConfirm();
            HttpContext.Session.Set(PENDING_TRANSFER, Encoding.UTF8.GetBytes(JsonSerializer.Serialize(Transfer)));
            return new ViewResult
            {
                ViewName = "TransferCheck",
                ViewData = ViewData
            };
        }

        private IActionResult TransferConfirmation(Transfer transfer, string accountType)
        {
            var principal = authenticationFacade.GetPrincipal();
            transfer.Username = principal.Identity!.Name;
            transfer.Date = DateTime.Now;

            var amount = transfer.Amount;
            transfer.Amount = InsecureBankUtils.Round(amount, 2);

            var feeAmount = transfer.Amount * transfer.Fee / 100.0;
            transfer.Fee = InsecureBankUtils.Round(feeAmount, 2);

            Type = accountType;
            transferFacade.CreateNewTransfer(transfer);

            Account = accountDao.FindUsersByUsername(transfer.Username).First();
            Transfer = transfer;
            
            return new ViewResult
            {
                ViewName = "TransferConfirmation",
                ViewData = ViewData
            };
        }
    }

    public static class AccountType
    {
        public const string PERSONAL = "Personal";

        public const string BUSINESS = "Business";
    }
}

Pages/User/UserDetail.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Formatters.Binary;
using insecure_bank_net.Bean;
using insecure_bank_net.Dao;
using insecure_bank_net.Facade;
using insecure_bank_net.Util;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace insecure_bank_net.Pages.User
{
    public class UserDetail : PageModel
    {
        private readonly IWebHostEnvironment environment;
        private readonly IAuthenticationFacade authenticationFacade;
        private readonly IAccountDao accountDao;
        private readonly ICreditAccountDao creditAccountDao;
        private readonly IStorageFacade storageFacade;

        public UserDetail(IWebHostEnvironment environment, IAuthenticationFacade authenticationFacade,
            IStorageFacade storageFacade,
            IAccountDao accountDao, ICreditAccountDao creditAccountDao)
        {
            this.environment = environment;
            this.authenticationFacade = authenticationFacade;
            this.storageFacade = storageFacade;
            this.accountDao = accountDao;
            this.creditAccountDao = creditAccountDao;
        }

        public Bean.Account Account { get; set; }

        public List<CreditAccount> CreditAccounts { get; set; }

        [BindProperty] public string Username { get; set; }

        [BindProperty] public string UsernameMalicious { get; set; }

        [BindProperty] public IFormFile Upload { get; set; }

        public void OnGet(string username)
        {
            var account = accountDao.FindUsersByUsername(username).First();
            var creditAccounts = creditAccountDao.FindCreditAccountsByUsername(account.Username);
            Account = account;
            Username = account.Username;
            UsernameMalicious = account.Username;
            CreditAccounts = creditAccounts;
        }

        public IActionResult OnGetCreditCardImage(string name)
        {
            var stream = new FileStream(environment.WebRootPath + $"\\img\\creditCards/{name}", FileMode.Open);
            return File(stream, "image/png", name);
        }

        public IActionResult OnGetAvatar(string name)
        {
            var image = $"\\img\\avatars\\{name}";
            var file = storageFacade.Exists(image)
                ? storageFacade.Load(image)
                : storageFacade.Load("\\img\\avatars\\avatar.png");
            return File(file, "image/png", name);
        }

        public IActionResult OnPostCertificate(string username)
        {
            var account = accountDao.FindUsersByUsername(username).First();
            var tmpFile = Path.GetTempFileName();
            var stream = new FileStream(tmpFile, FileMode.Create);
            var fos = new BinaryFormatter();
            fos.Serialize(stream, new FileUntrustedValid(account.Name));
            stream.Seek(0L, SeekOrigin.Begin);
            return File(stream, "application/octet-stream", $"Certificate_{account.Name}.jks");
        }

        public IActionResult OnPostMaliciousCertificate(string usernameMalicious)
        {
            var account = accountDao.FindUsersByUsername(usernameMalicious).First();
            var tmpFile = Path.GetTempFileName();
            var stream = new FileStream(tmpFile, FileMode.Create);
            var fos = new BinaryFormatter();
            fos.Serialize(stream, new FileUntrusted(account.Name));
            stream.Seek(0L, SeekOrigin.Begin);
            return File(stream, "application/octet-stream", $"MaliciousCertificate_{account.Name}.jks");
        }

        public IActionResult OnPostNewCertificate()
        {
            if (Upload != null && Upload.Length > 0)
            {
                var formatter = new BinaryFormatter();
                formatter.Deserialize(Upload.OpenReadStream());
                return Content("<p>File '" + Upload.FileName + "' uploaded successfully</p>", "text/html");
            }
            else
            {
                return Content("<p>No file uploaded", "text/html");
            }
        }

        public IActionResult OnPostUpdate()
        {
            var principal = authenticationFacade.GetPrincipal();
            var username = principal.Identity!.Name;
            if (Upload != null && Upload.Length > 0)
            {
                storageFacade.Save(Upload.OpenReadStream(), $"\\img\\avatars\\{username}.png");
            }

            return RedirectToPage("/User/UserDetail", new Dictionary<string, string> {{"username", username}});
        }
    }
}

Pages/User/NewTransfer.cshtml
@page "{handler?}"
@model insecure_bank_net.Pages.User.NewTransfer

@{
    ViewData["BodyClass"] = "static-tables";
}

<!-- WRAPPER -->
<div class="wrapper">
    <div class="container-fluid">
        <!-- TOP BAR -->
        <partial name="Shared/_TopBar" />
        <!-- END TOP BAR -->
        <div class="row">
            <div class="col-lg-2 col-left">
                <!-- LEFT CONTENT -->
                <div class="left-content">
                    <partial name="Shared/_MainNav" />
                </div>
            </div>
            <div class="col-lg-10 col-right ">
                <div class="right-content">
                    <!-- MAIN CONTENT -->
                    <div class="main-content">
                        <div class="primary-content">
                            <div class="heading clearfix">
                                <h2>MAKE A TRANSFER</h2>
                                <ul class="breadcrumb pull-left">
                                    <li>
                                        <i class="icon ion-home"></i><a asp-page="/User/Dashboard">Home</a>
                                    </li>
                                    <li>
                                        <a asp-page="/User/NewTransfer">Transfers</a>
                                    </li>
                                    <li>
                                        <a asp-page="/User/NewTransfer">Make a transfer</a>
                                    </li>
                                </ul>
                            </div>
                            <!-- RESPONSIVE TABLE -->
                            <div class="widget">
                                <div class="widget-header clearfix">
                                    <h3>
                                        <i class="fa fa-list-alt"></i> <span>NEW TRANSFER</span>
                                    </h3>
                                </div>
                                <div class="widget-content">
                                    <form method="post" class="form-horizontal" role="form" asp-page-handler="transfer">
                                        <div class="form-group">
                                            <label class="col-md-2 control-label">From Account</label>
                                            <div class="col-md-10">
                                                <select asp-for="Transfer.FromAccount" asp-items="Model.CashAccounts" class="form-control">
                                                </select>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="col-md-2 control-label">Send To</label>
                                            <div class="col-md-10">
                                                <input asp-for="Transfer.ToAccount" type="text" class="form-control" required="required"/>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="col-md-2 control-label">Description</label>
                                            <div class="col-md-10">
                                                <input asp-for="Transfer.Description" type="text" class="form-control" required="required"/>
                                                @foreach (var modelError in Html.ViewData.ModelState.Where(it => it.Key == "Input.Description").SelectMany(keyValuePair => keyValuePair.Value.Errors))
                                                {
                                                    <span class="text-danger">@modelError.ErrorMessage</span>
                                                }
                                                <form:errors path="description" cssClass="text-danger"/>
                                            </div>
                                        </div>

                                        <div class="form-group ${error eq true  ? 'has-error has-feedback' : ''}">
                                            <label class="col-sm-2 control-label">Amount</label>
                                            <div class="col-sm-10">
                                                <div class="input-group">
                                                    <input asp-for="Transfer.Amount" type="text" class="form-control"/>
                                                    <span class="input-group-addon">&#8364;</span>
                                                </div>
                                                @foreach (var modelError in Html.ViewData.ModelState.Where(it => it.Key == "Input.Amount").SelectMany(keyValuePair => keyValuePair.Value.Errors))
                                                {
                                                    <span class="text-danger">@modelError.ErrorMessage</span>
                                                }
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-sm-12">
                                                <div class="pull-right">
                                                    <button type="submit" class="btn btn-primary">Send</button>
                                                </div>
                                            </div>
                                        </div>

                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT -->
        </div>
    </div>
</div>
<div class="left-content-bg col-md-2"></div>
<!-- END WRAPPER -->

@section Styles {
    <partial name="Shared/_Styles"/>
}

Pages/User/TransferCheck.cshtml
@model NewTransfer

@{
    ViewData["BodyClass"] = "static-tables";
}

<div class="wrapper">
	<div class="container-fluid">
		<!-- TOP BAR -->
		<partial name="Shared/_TopBar" />
		<!-- END TOP BAR -->
		<div class="row">
			<div class="col-lg-2 col-left">
				<!-- LEFT CONTENT -->
				<div class="left-content">
					 <partial name="Shared/_MainNav" />
				</div>
			</div>
			<div class="col-lg-10 col-right ">
				<div class="right-content">
					<!-- MAIN CONTENT -->
					<div class="main-content">
						<div class="primary-content">
							<div class="heading clearfix">
								<h2>MAKE A TRANSFER</h2>
							</div>

							<div class="widget-content">
								<h4>DETAILS CONFIRMATION</h4>
								<table id="user" class="table table-bordered table-striped">
									<tbody>
									<tr>
										<td>
											<label class="col-md-4 control-label">From Account</label>
										</td>
										<td>
											@Model.Transfer.FromAccount
										</td>
									</tr>
									<tr>
										<td>
											<label class="col-md-4 control-label">Send To</label>
										</td>
										<td>
											@Model.Transfer.ToAccount
										</td>
									</tr>
									<tr>
										<td>
											<label class="col-md-4 control-label">Description</label>
										</td>
										<td>@Html.Raw(Model.Transfer.Description)</td>
									</tr>
									<tr>
										<td>
											<label class="col-md-4 control-label">Amount</label>
										</td>
										<td>@($"{Model.Transfer.Amount:N}") &#8364;</td>
									</tr>
									<tr>
										<td>
											<label class="col-md-4 control-label">Fee</label>
										</td>
										<td>@($"{Model.Transfer.Fee:N}") &#8364;</td>
									</tr>
									</tbody>
								</table>
							</div>

							<!-- RESPONSIVE TABLE -->
							<div class="widget">
								<div class="widget-header clearfix">
									<h3>
										<i class="fa fa-list-alt"></i> <span>Find the number 243 and enter the corresponding code:</span>
									</h3>
								</div>
								<div class="widget-content">
									<form method="post" class="form-horizontal" role="form" asp-page="/User/NewTransfer" asp-page-handler="confirm">
										<div class="form-group">
											<label class="col-md-2 control-label">Code</label>
											<div class="col-md-1">
												<input asp-for="Confirm.Code" type="text" class="form-control" maxlength="4"/>
											</div>
											<div class="col-md-6">
												<input asp-for="Confirm.Action" type="submit" class="btn btn-primary" value="Confirm" />
												<input asp-for="Confirm.Action" type="submit" class="btn btn-primary" value="Cancel" />
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- END MAIN CONTENT -->
		</div>
	</div>

</div>
<div class="left-content-bg col-md-2"></div>
<!-- END WRAPPER -->

@section Styles {
	<partial name="Shared/_Styles"/>
}

Pages/User/UserDetail.cshtml
@page "{handler?}"
@model insecure_bank_net.Pages.User.UserDetail

@{
    ViewData["BodyClass"] = "static-tables";
}

<!-- WRAPPER -->
<div class="wrapper">
    <div class="container-fluid">
        <!-- TOP BAR -->
        <partial name="Shared/_TopBar" />
        <!-- END TOP BAR -->
        <div class="row">
            <div class="col-lg-2 col-left">
                <!-- LEFT CONTENT -->
                <div class="left-content">
                    <partial name="Shared/_MainNav" />
                </div>
            </div>
            <div class="col-lg-10 col-right ">
                <div class="right-content">
                    <!-- MAIN CONTENT -->
                    <div class="main-content">
                        <div class="primary-content">
                            <div class="heading clearfix">
                                <h2>USER DETAIL</h2>
                                <ul class="breadcrumb pull-left">
                                    <li>
                                        <i class="icon ion-home"></i><a asp-page="/User/Dashboard">Home</a>
                                    </li>
                                    <li><a href="#">User detail</a></li>
                                </ul>
                            </div>
	                        <div class="row">
		                        <div class="col-sm-9">
			                        <div class="col-sm-2">
				                        <img id="userAvatarImage"  src="@Url.Page("/User/UserDetail","Avatar",new {name=Model.Account.Username + ".png" })" class="img-thumbnail" alt="avatar" style="border:solid 1px grey;cursor:pointer;"/>
				                        <form id="userAvatarForm" asp-page-handler="update" method="POST" style="display:none" enctype="multipart/form-data">
					                        <input id="userAvatarInput" type="file" asp-for="Upload"/>
				                        </form>
			                        </div>
			                        <div class="col-sm-10">
				                        <dl class="dl-horizontal">
					                        <dt>Current Date:</dt>
					                        <dd>@DateTime.Now.ToString("dd-MM-yyyy HH:mm")</dd>
					                        <dt>Register Date:</dt>
					                        <dd>20-09-2014</dd>
					                        <dt>Username:</dt>
					                        <dd>@Html.Raw(Model.Account.Username)</dd>
					                        <dt>Name:</dt>
					                        <dd>@Html.Raw(Model.Account.Name)</dd>
					                        <dt>Surname:</dt>
					                        <dd>@Html.Raw(Model.Account.Surname)</dd>
					                        <dt>Account Type:</dt>
					                        <dd>Personal</dd>
					                        <dt>Account Status:</dt>
					                        <dd>
						                        <span class="label label-success">ACTIVE</span>
					                        </dd>
					                        <dt style="padding: 10px 0px 10px 0px;">Digital Certificate:</dt>
					                        <dd style="padding: 10px 0px 10px 0px;">
						                        <form asp-page-handler="Certificate" method="POST" class="form-horizontal" role="form">
							                        <input type="hidden" asp-for="Username" />
							                        <button type="submit">Download</button>
						                        </form>
					                        </dd>
					                        <dt style="padding: 10px 0px 10px 0px;">Malicious Certificate:</dt>
					                        <dd style="padding: 10px 0px 10px 0px;">
						                        <form asp-page-handler="MaliciousCertificate" method="POST" class="form-horizontal" role="form">
							                        <input type="hidden" asp-for="UsernameMalicious" />
							                        <button type="submit">Download</button>
						                        </form>
					                        </dd>
					                        <dt style="padding: 10px 0px 10px 0px;">
						                        Upload
						                        new certificate:
					                        </dt>
					                        <dd style="padding: 10px 0px 10px 0px;">

						                        <form asp-page-handler="NewCertificate" method="POST" enctype="multipart/form-data">
							                        <input id="file" type="file" asp-for="Upload"/>
							                        <button type="submit" style="margin-top: 5px;">Upload</button>
						                        </form>
					                        </dd>

					                        <dt>Credit cards:</dt>
					                        <br>
					                        <dd>
						                        <div class="table-responsive">
							                        <table class="table table-condensed">
								                        <thead>
									                        <tr>
										                        <th>Cash Account</th>
										                        <th>Description</th>
									                        </tr>
								                        </thead>
								                        <tbody>
															@foreach (var credit in Model.CreditAccounts)
															{
																<tr>
																	<td>
																		@{ string creditImage; }
																		@if (credit.Description.Contains("Visa")) { creditImage = "visa.png"; }
																		else if (credit.Description.Contains("AmEx")) { creditImage = "amex.png"; }
																		else { creditImage = "mastercard.png"; }
																		<img id="card-ico" src="@Url.Page("/User/UserDetail","CreditCardImage",new {name=creditImage })" class="img-thumbnail" alt="card" style="border:solid 1px grey;cursor:pointer;"/>
																		@credit.Number
																	</td>
																	<td>@credit.Description</td>
																</tr>
															}
								                        </tbody>
							                        </table>
						                        </div>
					                        </dd>
				                        </dl>
			                        </div>
		                        </div>
	                        </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT -->
        </div>
    </div>
</div>
<div class="left-content-bg col-md-2"></div>
<!-- END WRAPPER -->

@section Scripts {
	<script>
		$(function(){
			$('#userAvatarImage').click(function(){
				$('#userAvatarInput').click();
			});
			$('#userAvatarInput').change(function(){
				$('#userAvatarForm').submit();
			});
		});
	</script>
}

@section Styles {
    <partial name="Shared/_Styles"/>
}